server:
  port: 80

spring:
  profiles:
    active: dev
  datasource:
    continue-on-error: true
    hikari:
      connection-test-query: SELECT DISTINCT 1 FROM sys_user
      maximum-pool-size: 50
      connection-timeout: 3000
      validation-timeout: 3000
