server:
  port: 8080
  session:
    #session 失效时间 单位是秒 ,实际session失效时间不能低于一分钟
    timeout: 3600

spring:
  profiles:
    active: dev
  datasource:
    continue-on-error: true
    hikari:
      connection-test-query: SELECT DISTINCT 1 FROM sys_user
      maximum-pool-size: 50
      connection-timeout: 3000
      validation-timeout: 3000
