spring:
  datasource:
    url: jdbc:mysql://192.168.0.223:3306/dog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.0.223
    port: 6379
    password: 123456
  rabbitmq:
    host: 192.168.0.223
    port: 5672
    username: dog
    password: 123456

dog:
  security:
    brower:
      login-page: /dog-singIn.html
      login-response-type: JSON
    code:
      image:
        url:
    social:
      filter-processes-url: /qqLogin
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        provider-id: callback.do
logging:
  level:
   com.github.xm.common.mapper: debug
   com.github.xm.upms.mapper: debug
